// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonRepo: typeof import('./src/components/ButtonRepo.vue')['default']
    Examplesix: typeof import('./src/components/examplesix.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Links: typeof import('./src/components/Links.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    PeopleSort: typeof import('./src/components/peopleSort.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
